"""ServiceNow Tickets — every ticket the agent created, filterable by
status / severity / host. The mock store mirrors a real ServiceNow Incident
table; status transitions are clickable inline.
"""

from __future__ import annotations

import os
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import pandas as pd
import streamlit as st

from services.servicenow_mock.client import update_ticket_status
from ui.lib.data import fetch_tickets, invalidate_caches
from ui.lib.styles import SEVERITY_COLORS, TICKET_STATUS_COLORS

st.set_page_config(page_title="OpsGPT — Tickets", page_icon="📨", layout="wide")

st.title("📨 ServiceNow Tickets")
st.caption(
    "Auto-generated by OpsGPT when the Decision Engine routes a run to "
    "`ticket_only` or the verdict is `escalated_anomaly`. The mock store "
    "mirrors ServiceNow's Incident shape — same lifecycle, same fields."
)

if st.button("🔄 Refresh"):
    invalidate_caches()
    st.rerun()


# ---------------------------------------------------------------------------
# Filters
# ---------------------------------------------------------------------------
all_tickets = fetch_tickets(limit=500)
if all_tickets.empty:
    st.info(
        "No tickets yet. Tickets are created automatically when the agent "
        "escalates an anomaly or routes to ticket_only. Run the agent on a "
        "host with an anomaly to create one."
    )
    st.stop()

with st.expander("Filters", expanded=False):
    c1, c2, c3 = st.columns(3)
    status_filter = c1.multiselect(
        "Status",
        sorted(all_tickets["status"].unique().tolist()),
    )
    severity_filter = c2.multiselect(
        "Severity",
        sorted(all_tickets["severity"].unique().tolist()),
    )
    host_filter = c3.multiselect(
        "Host",
        sorted(all_tickets["host_id"].dropna().unique().tolist()),
    )

filtered = all_tickets.copy()
if status_filter:
    filtered = filtered[filtered["status"].isin(status_filter)]
if severity_filter:
    filtered = filtered[filtered["severity"].isin(severity_filter)]
if host_filter:
    filtered = filtered[filtered["host_id"].isin(host_filter)]


# ---------------------------------------------------------------------------
# Summary metrics
# ---------------------------------------------------------------------------
m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("Total", len(filtered))
m2.metric("New", int((filtered["status"] == "new").sum()))
m3.metric("In progress", int((filtered["status"] == "in_progress").sum()))
m4.metric("Resolved", int((filtered["status"] == "resolved").sum()))
m5.metric("P1+P2", int(filtered["severity"].isin(["P1", "P2"]).sum()))

st.markdown("---")


# ---------------------------------------------------------------------------
# Ticket list
# ---------------------------------------------------------------------------
def _badge(value: str, palette: dict) -> str:
    color = palette.get(value, "#6b7280")
    return (
        f"<span style='background:{color}; color:white; padding:2px 8px; "
        f"border-radius:6px; font-size:0.85em; font-weight:600;'>{value}</span>"
    )


for _, t in filtered.iterrows():
    sev_html = _badge(t["severity"], SEVERITY_COLORS)
    status_html = _badge(t["status"], TICKET_STATUS_COLORS)
    header = (
        f"**{t['ticket_id']}** · {t['short_description']} · "
        f"{t['created_at'].strftime('%Y-%m-%d %H:%M')}"
    )

    with st.expander(header, expanded=False):
        c1, c2 = st.columns([2, 1])
        with c1:
            st.markdown(
                f"{sev_html} &nbsp; {status_html} &nbsp;"
                f"<span style='color:#6b7280;'>· assignment: <code>{t['assignment_group']}</code> · host: <code>{t['host_id']}</code></span>",
                unsafe_allow_html=True,
            )
            st.markdown("**Description**")
            st.code(t["description"], language="text")

        with c2:
            st.markdown("**Lifecycle**")
            current = t["status"]
            options = ["new", "assigned", "in_progress", "resolved", "closed"]
            new_status = st.selectbox(
                "Set status",
                options,
                index=options.index(current),
                key=f"status_{t['ticket_id']}",
            )
            if new_status != current:
                if st.button("Update", key=f"update_{t['ticket_id']}"):
                    update_ticket_status(t["ticket_id"], new_status)
                    invalidate_caches()
                    st.success(f"Status updated to '{new_status}'.")
                    st.rerun()

            st.markdown("**Linked**")
            st.write({
                "agent_run_id": t["agent_run_id"],
                "metadata": t.get("metadata") or {},
            })
