"""Mock ServiceNow client.

In production this module would talk to the customer's ServiceNow instance
via REST (`/api/now/table/incident`). For the POC it inserts rows into the
`servicenow_tickets` table — same fields, same lifecycle, same audit trail.

Severity + assignment-group selection encodes simple rules that match the
runbook content in the RAG corpus:
  - escalated_anomaly → P2, app team for that role (anomalies need eng)
  - ticket_only with imminent forecast (<24h) → P2, infra-capacity
  - ticket_only with farther forecast → P3, infra-capacity
  - operator-denied via OpsGPT chatbot → P3, infra-capacity (informational)
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

from shared.db import timescale_conn
from shared.schemas import AgentRun, MLPrediction, ServiceNowTicket, Severity

log = logging.getLogger(__name__)


def _next_ticket_id(now: datetime) -> str:
    """Emit a ServiceNow-style INC ticket number, monotonic per-month."""
    prefix = now.strftime("INC-%Y-%m-")
    with timescale_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT COALESCE(
                    MAX(CAST(split_part(ticket_id, '-', 4) AS INT)),
                    0
                ) AS last_seq
                FROM servicenow_tickets
                WHERE ticket_id LIKE %s
                """,
                (prefix + "%",),
            )
            row = cur.fetchone()
    seq = (row["last_seq"] if row else 0) + 1
    return f"{prefix}{seq:04d}"


def _classify(
    *,
    decision: Optional[str],
    verdict: Optional[str],
    role: str,
    hours_to_90pct: Optional[float],
    anomaly_score: Optional[float],
) -> tuple[Severity, str, str]:
    """Return (severity, assignment_group, short_description)."""
    role = role or "app"

    if verdict == "escalated_anomaly":
        return (
            "P2",
            f"App-Support-{role}",
            f"Anomalous disk growth on {{host}} — investigate upstream",
        )
    if hours_to_90pct is not None and hours_to_90pct < 24:
        return (
            "P2",
            "Infra-Capacity",
            f"Disk projected to breach 90% within 24h on {{host}}",
        )
    if decision == "ticket_only":
        return (
            "P3",
            "Infra-Capacity",
            f"Predictive disk-fill warning for {{host}}",
        )
    return (
        "P3",
        "Infra-Capacity",
        f"OpsGPT review for {{host}}",
    )


def _format_description(
    host_id: str,
    role: str,
    environment: str,
    monitored_path: str,
    prediction: Optional[MLPrediction],
    agent_run: AgentRun,
) -> str:
    p = prediction
    forecast_block = (
        f"  forecast 1d: {p.forecast_1d_pct:.1f}%\n"
        f"  forecast 3d: {p.forecast_3d_pct:.1f}%\n"
        f"  forecast 7d: {p.forecast_7d_pct:.1f}%\n"
        f"  forecast 14d: {p.forecast_14d_pct:.1f}%\n"
        f"  hours to 90%: {p.hours_to_90pct or 'n/a'}\n"
        f"  anomaly score: {p.anomaly_score:.3f}\n"
    ) if p is not None else "  (no recent ML prediction)\n"

    return (
        f"Auto-generated by OpsGPT predictive disk-management.\n\n"
        f"AFFECTED CI\n"
        f"  host_id:        {host_id}\n"
        f"  role:           {role}\n"
        f"  environment:    {environment}\n"
        f"  monitored_path: {monitored_path}\n\n"
        f"ML SIGNALS\n{forecast_block}\n"
        f"AGENT VERDICT\n"
        f"  decision: {agent_run.decision}\n"
        f"  verdict:  {agent_run.verdict}\n"
        f"  confidence_score: {agent_run.confidence_score}\n"
        f"  agent_run_id:     {agent_run.run_id}\n\n"
        f"REASONING\n{agent_run.llm_reasoning or '(none)'}\n\n"
        f"NEXT STEPS\n"
        f"  1. Review the agent's reasoning above against host telemetry\n"
        f"  2. Inspect the affected directory on {host_id}\n"
        f"  3. If anomalous: identify upstream cause (logger config, deploy, etc.)\n"
        f"  4. If capacity: evaluate volume expansion vs. retention adjustment\n"
    )


def create_ticket_from_run(
    agent_run: AgentRun,
    host_metadata: dict,
    prediction: Optional[MLPrediction] = None,
) -> ServiceNowTicket:
    """Convert one agent run into a ServiceNow ticket and persist it."""
    role = host_metadata.get("role", "app")
    environment = host_metadata.get("environment", "prod")
    monitored = host_metadata.get("monitored_path", "/")

    severity, assignment, short_template = _classify(
        decision=agent_run.decision,
        verdict=agent_run.verdict,
        role=role,
        hours_to_90pct=prediction.hours_to_90pct if prediction else None,
        anomaly_score=prediction.anomaly_score if prediction else None,
    )
    short_description = short_template.format(host=agent_run.host_id)
    description = _format_description(
        agent_run.host_id, role, environment, monitored, prediction, agent_run
    )

    now = datetime.now(timezone.utc)
    ticket_id = _next_ticket_id(now)
    ticket = ServiceNowTicket(
        ticket_id=ticket_id,
        created_at=now,
        updated_at=now,
        status="new",
        severity=severity,
        short_description=short_description,
        description=description,
        host_id=agent_run.host_id,
        assignment_group=assignment,
        agent_run_id=agent_run.run_id,
        metadata={
            "decision": agent_run.decision,
            "verdict": agent_run.verdict,
            "confidence_score": agent_run.confidence_score,
        },
    )

    with timescale_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO servicenow_tickets
                  (ticket_id, created_at, updated_at, status, severity,
                   short_description, description, host_id, assignment_group,
                   agent_run_id, metadata)
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb)
                """,
                (
                    ticket.ticket_id, ticket.created_at, ticket.updated_at,
                    ticket.status, ticket.severity, ticket.short_description,
                    ticket.description, ticket.host_id, ticket.assignment_group,
                    ticket.agent_run_id,
                    __import__("json").dumps(ticket.metadata),
                ),
            )
            cur.execute(
                "UPDATE agent_runs SET servicenow_ticket_id = %s WHERE run_id = %s",
                (ticket.ticket_id, agent_run.run_id),
            )
        conn.commit()

    log.info(
        "[ServiceNow mock] created %s severity=%s host=%s assignment=%s",
        ticket.ticket_id, ticket.severity, ticket.host_id, ticket.assignment_group,
    )
    return ticket


def list_tickets(
    status: Optional[str] = None,
    severity: Optional[str] = None,
    limit: int = 200,
) -> list[ServiceNowTicket]:
    sql = "SELECT * FROM servicenow_tickets"
    where = []
    params: list = []
    if status:
        where.append("status = %s")
        params.append(status)
    if severity:
        where.append("severity = %s")
        params.append(severity)
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += " ORDER BY created_at DESC LIMIT %s"
    params.append(limit)

    with timescale_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, tuple(params))
            rows = cur.fetchall()
    return [ServiceNowTicket.model_validate(r) for r in rows]


def update_ticket_status(ticket_id: str, new_status: str) -> ServiceNowTicket:
    with timescale_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE servicenow_tickets
                SET status = %s, updated_at = NOW()
                WHERE ticket_id = %s
                RETURNING *
                """,
                (new_status, ticket_id),
            )
            row = cur.fetchone()
        conn.commit()
    if row is None:
        raise ValueError(f"ticket not found: {ticket_id}")
    return ServiceNowTicket.model_validate(row)
